### PR TITLE
Allow passing arguments to "none" rake BuildCommands

### PR DESCRIPTION
**Pull request by STRUDSO**

### CODE REVIEW

**Comment by mavnn** [comment]
Hi all,
any news on when this might get merged? I came to submit an almost identical pull request as this issue is a blocker to us adopting ripple - which would otherwise save us a lot of headaches!

Thanks!

**Comment by jmarnold** [comment]
I'll pull this one in tonight.

**Comment by jmarnold** [comment]
And by "tonight", I mean today. Sorry, guys.

**Comment by jmarnold** [comment]
Got it

**Pull request closed without merging**
