### PR TITLE
PackageParams introduced

### PR DESCRIPTION
**Pull request by Scooletz**

### CODE REVIEW

**Comment by jmarnold** [comment]
Are you sure you rebased this on master? I just pulled this down and it's completely missing all of the symbols package work from @ptrstpp950

**Comment by jmarnold** [comment]
I'm pulling all of your work into a local 2.1 branch and rebasing the work on top of itself. 109 and 106 are fine but 107 is definitely behind.

**Comment by Scooletz** [comment]
As far as I can see on the graph https://github.com/Scooletz/ripple/branches and checking via log, the SolutionPackageParamObject branch is 2 commits ahead and no behind. Am I missing something?

**Comment by jmarnold** [comment]
Do you have an "upstream" defined to point at ripple master? If so, try this from your branch:

git fetch upstream
git rebase upstream/master

**Comment by Scooletz** [comment]
Thanks Josh. I got it. I'll push it as soon as I deal with conflicts.

**Comment by Scooletz** [comment]
Rebased & pushed to branch. Waiting for pull.

**Comment by jmarnold** [comment]
Working on this right now. All of your PRs and the issues in Milestone 2.1 are going to mark the 2.1 release. I'm gunning for this Friday but I'll push it to a public 2.1 branch here in a few.

**Comment by jmarnold** [comment]
Pushed the public branch.

**Comment by Scooletz** [comment]
Cool! Thanks Josh!

**Comment by Scooletz** [comment]
Ugh. One more thing. May I delete all my pull-request branches? What's the strategy behind 2.1? Will be the new master soon, or are you waiting for some additional changes for the master?

**Comment by jmarnold** [comment]
You can delete your branches since those commits are in now. Normally I just work straight out of master but I had a couple of things I wanted to do before I go into master with the 2.1 version.

This will be into master by Friday at the latest. If you want it in sooner, I can try to move things around, though.

**Comment by Scooletz** [comment]
Nope. That's fine. I was not aware of the Ripple's workflow. But as far as I see it, it works perfectly for me.

**Comment by jmarnold** [comment]
Do you use ripple from ruby gems like we do? Or are you just adding it to your environment path?

**Comment by jmarnold** [comment]
When I've got fixes I want to use locally, I just run

> rake gem:install

As long as your gemfile specifies ripple-cli, "~>2.0" the local build will get used. It's a handy trick -- especially since ripple depends on ripple ;)

**Comment by Scooletz** [comment]
I use ripple in a much less sophisticated way. A tag is built from the sources and added to the repository (SVN repo, ripple as external for all). I didn't invest time to setup rake yet.
Yes, I'm aware of the dependency:P

**Pull request closed without merging**
