### PR TITLE
Caching on multiple levels

### PR DESCRIPTION
**Pull request by Scooletz**
A few levels of caching:
- FeedService caches results of its methods (DependenciesFor, NugetFor) according to depdency and mode passed as parameters
- implementors of INugetFeed cache FindLatest, Find results, including nulls returned by a given nuget feed

This result in a performance boost for projects with a quite complex dependency graph.

### CODE REVIEW

**Comment by jmarnold** [comment]
Thanks for this. I'll review and pull it in no later than this afternoon.

**Comment by jmarnold** [comment]
Aside from differences in coding style, I think the only thing I would've done differently is use FubuCore's Cache<,> utility type rather than inlining the dictionary usage.

I rebased this on top of master locally and I'm seeing a breaking test in the FileSystemFeedTester. Do you think you could rebase and run through that one?

**Comment by Scooletz** [comment]
Will run the test. I'll add Cache<,> usage as well.

**Comment by Scooletz** [comment]
I pushed the rebased branch with force. Hope this will not blow up the merging. Waiting for your comments.

**Pull request merged**
