### PR TITLE
Project override

### PR DESCRIPTION
**Pull request by andreasohlund**
@SimonCropp quick review. I've also fixed an issue with deps missing from the "solution" => think that was the hack you mentioned earlier today:

https://github.com/Particular/ripple/compare/DarthFubuMVC:3.0...project-override?expand=1#L1R37

### CODE REVIEW

**Comment by andreasohlund** [comment]
@jeremydmiller @jmarnold This was meant to go on our internal fork but since I screwed that up I might as well get your input on this :)

We mainly have a situation where some of our projects have a csproj reference and that causes nuget (correctly) to skip adding  nuspec ref since its assumed that project refs are included in the nuget it self. 

This is not always the case for us so I've added a extra condition to check if the project ref happens to have its own nuget:

https://github.com/Particular/ripple/commit/e03e27c59f0a66a81bc9064771b4de1a33c35b27#L1R74

This now works for us but the code is crap, can I improve on the detection to skip the ugly string.Split?

https://github.com/Particular/ripple/commit/e03e27c59f0a66a81bc9064771b4de1a33c35b27#L1R82

I've also (should have been a separate pull ) made sure that we don't create duplicates in the nuspec deps:

https://github.com/Particular/ripple/commit/e03e27c59f0a66a81bc9064771b4de1a33c35b27#L0R63

So consider this a work in progress!

Thoughts, comments?

**Comment by jeremydmiller** [comment]
@jmarnold, this might be a good excuse for introducing FubuCsProjFile.  We _could_ use that library to interrogate the csproj files for project links and add that into the mix.

**Comment by andreasohlund** [comment]
This pull also fixes https://github.com/DarthFubuMVC/ripple/issues/203

**Comment by jmarnold** [comment]
I think I'm going to pull this is one as is. I'm rethinking the Nuspec generation based on all the feedback your team has given us (for 3.0+).

**Comment by jmarnold** [comment]
Can I get you to rebase and make sure this is still working? I'll pull it in right away.

**Comment by andreasohlund** [comment]
Isn't this already pulled in:
https://github.com/DarthFubuMVC/ripple/commit/e03e27c59f0a66a81bc9064771b4de1a33c35b27
 ?

On Tue, Oct 8, 2013 at 5:20 PM, Josh Arnold notifications@github.comwrote:

> Can I get you to rebase and make sure this is still working? I'll pull it
> in right away.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DarthFubuMVC/ripple/pull/208#issuecomment-25899434
> .

## 

Andreas Öhlund****

Director of Engineering, Particular Software****

---

( Direct  +46.72.2358806****

"   Web    Particular.net http://www.particular.net/
*\* *Email  andreas.ohlund@particular.net

**Comment by jmarnold** [comment]
Whoops, I think you're right.

**Comment by jmarnold** [comment]
@andreasohlund Can you remind me why you needed the string.Split here?

**Comment by andreasohlund** [comment]
Ifaik the csProjRef is in the format "TheNameOfTheProject TheDisplayName"
hence the need to get the first?

**Comment by jmarnold** [comment]
Ah ha, ok.

**Pull request merged**
