### PR TITLE
Rescue when bundler is missing

### PR DESCRIPTION
**Pull request by mtscout6**
Here is a potential idea for ensuring that bundler is installed for those who pull down a fresh clone. The basic idea here is that we can rescue a LoadError in ruby if we fail to require in bundler. Then we can just install it for them. Also, we can re-attempt to run the same command that they originally tried. This can stand as a model for the rakefiles of each repo, so I'd like to get it right in one before I work to roll it out to each of the others.

### CODE REVIEW

**Comment by jeremydmiller** [comment]
I like this a lot.  Thanks for doing this, and I will definitely pull this one in tomorrow (5/3) when I get back to build scripts

**Comment by jeremydmiller** [comment]
@mtscout6,

Playing with this a little bit with FubuCore and the new fuburake.  It does help when you don't have bundler installed at all.  When you're missing one of the other gems, you just get a message to run "bundle install"

I think I wanna declare victory with this.

**Comment by mtscout6** [comment]
The only reason I was wanting to investigate it further was so each build
wouldn't need both a bundle install step and rake. It would be nice if we
can merge them both into rake. I have not had the time yet to investigate
that possibility. I will take a quick look at it tomorrow morning.

**Comment by mtscout6** [comment]
Ryan and I found an issue with this, since we are exiting with 0 we could be telling Teamcity that everything is ok, when in reality it may not be. We need to bubble up the actually exit code from the child process we spin off.

**Comment by jmarnold** [comment]
We got this in.

**Pull request closed without merging**
