### PR TITLE
Solution now allows override the default NugetFolderCache

### PR DESCRIPTION
**Pull request by Scooletz**

### CODE REVIEW

**Comment by jmarnold** [comment]
I was thinking that the default would always be used unless overridden via the command line "--cache" flag. Any reason why that wouldn't work?

**Comment by Scooletz** [comment]
One might want to setup all the commands in one place, for the whole solution. Beside, the currently used Environment.SpecialFolder.ApplicationData is a roaming folder which makes your roaming Windows profile heavier. This may influence people working with roaming profiles (like me).

**Comment by jmarnold** [comment]
Gotcha. I like that.

**Comment by jmarnold** [comment]
Got it. 4f7339f8e989b7920e7118b0f1bf4c25ed320f59

**Pull request closed without merging**
