### PR TITLE
Add symbols to create package fix

### PR DESCRIPTION
**Pull request by ptrstpp950**
I added possibility to create symbol packages aside to normal packages

### CODE REVIEW

**Comment by jmarnold** [comment]
Can I get you to rebase this on master?

**Comment by ptrstpp950** [comment]
What do you mean? I do not know how should I do this.

**Comment by CoreyKaylor** [comment]
Is this helpful?
http://fubu-project.org/contribute/

**Comment by ptrstpp950** [comment]
@CoreyKaylor  Thanks it was helpful
@jmarnold  I hope now it is ok.

**Comment by jmarnold** [comment]
@ptrstpp950 This is still pretty behind master. I tried rebasing it myself but I'm seeing a merge conflict that would be much easier for you to handle since I'm not entirely sure what was changed yet.

**Comment by jmarnold** [comment]
Can you try this from your local branch?

git fetch upstream
git rebase upstream/master

**Comment by ptrstpp950** [comment]
Ok Now I see merge errors. I will commit this later.

**Comment by jmarnold** [comment]
I think @Scooletz was working on something to collapse the packaging methods to use a context object vs. all of the arguments. Did that ever get anywhere? This is proving the usefulness of that idea.

**Comment by Scooletz** [comment]
I'm here! ;-) I'll push as soon as this get accepted. I don't want to mess as this is touching the very same area. If there are any more doubts about this, I can make it now in branch based on your master. I'd prefer not to blow up this pull request with another change.

**Comment by jmarnold** [comment]
Ah, good call. That's fine, we can wait.

**Comment by Scooletz** [comment]
So as soon as this is introduced you can await my pull request.

**Comment by jmarnold** [comment]
I like it :)

**Comment by ptrstpp950** [comment]
Now it is ok?

**Comment by jmarnold** [comment]
Closed via 8e3728051a9f230053501d69bc5924d7e36dfde2

**Pull request closed without merging**
