### PR TITLE
Floating feeds now honor stability settings

### LINKED ISSUE #211: Floating feeds doesn't honor stability
Floating feeds will always get the latest unstable version from the feed even if stability is set to ReleasedOnly

### PR DESCRIPTION
**Pull request by andreasohlund**
Closes #211

### CODE REVIEW

**Comment by jmarnold** [comment]
@andreasohlund Did you branch off of master? Jeremy made a fix a while ago to address an issue of Nuget throttling the number of results:

https://github.com/DarthFubuMVC/ripple/blob/master/src/ripple/Nuget/FloatingFeed.cs

**Comment by andreasohlund** [comment]
No I branched of 3.0, can you merge or do U want me to rebase off master?

**Comment by jeremydmiller** [comment]
Hey Andreas,

Can you rebase that off of master?  I think 3.0 is just too far away.  I just pushed 2.3.3 w/ some of your fixes and a Mono fix I wanted, but I can push 2.3.4 whenever.

Thanks,

Jeremy

**Comment by andreasohlund** [comment]
Replaced by https://github.com/DarthFubuMVC/ripple/pull/215

**Pull request closed without merging**
